// stubs/inertia/svelte/LoginCodeVerify.svelte
<script>
    import { useForm } from '@inertiajs/svelte'

    export let email

    const form = useForm({ code: '' })
</script>

<form on:submit|preventDefault={() => form.post(route('passwordless.login-code.authenticate'))}>
    <div>
        <label for="code">Enter your login code</label>
        <input
            id="code"
            type="text"
            bind:value={$form.code}
            placeholder="123456"
            autocomplete="one-time-code"
            required
        />
        {#if $form.errors.code}
            <span>{$form.errors.code}</span>
        {/if}
    </div>

    <button type="submit" disabled={$form.processing}>
        Verify code
    </button>
</form>

// stubs/inertia/react/LoginCodeVerify.jsx
import { useForm } from '@inertiajs/react'

export default function LoginCodeVerify({ email }) {
    const { data, setData, post, processing, errors } = useForm({ code: '' })

    function submit(e) {
        e.preventDefault()
        post(route('passwordless.login-code.authenticate'))
    }

    return (
        <form onSubmit={submit}>
            <div>
                <label htmlFor="code">Enter your login code</label>
                <input
                    id="code"
                    type="text"
                    value={data.code}
                    onChange={e => setData('code', e.target.value)}
                    placeholder="123456"
                    autoComplete="one-time-code"
                    required
                />
                {errors.code && <span>{errors.code}</span>}
            </div>

            <button type="submit" disabled={processing}>
                Verify code
            </button>
        </form>
    )
}
